// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type Kind uint32

const (
	KindNil        Kind = 0
	KindInt        Kind = 1
	KindInt8       Kind = 2
	KindInt16      Kind = 3
	KindInt32      Kind = 4
	KindInt64      Kind = 5
	KindUint8      Kind = 6
	KindUint16     Kind = 7
	KindUint32     Kind = 8
	KindUint64     Kind = 9
	KindUintptr    Kind = 10
	KindFloat32    Kind = 11
	KindFloat64    Kind = 12
	KindComplex64  Kind = 13
	KindComplex128 Kind = 14
	KindString     Kind = 15
	KindRune       Kind = 16
	KindByte       Kind = 17
	KindBoolean    Kind = 18
	KindPointer    Kind = 19
	KindStruct     Kind = 20
	KindFunc       Kind = 21
	KindArray      Kind = 22
	KindSlice      Kind = 23
	KindMap        Kind = 24
	KindChannel    Kind = 25
	KindInterface  Kind = 26
)

var EnumNamesKind = map[Kind]string{
	KindNil:        "Nil",
	KindInt:        "Int",
	KindInt8:       "Int8",
	KindInt16:      "Int16",
	KindInt32:      "Int32",
	KindInt64:      "Int64",
	KindUint8:      "Uint8",
	KindUint16:     "Uint16",
	KindUint32:     "Uint32",
	KindUint64:     "Uint64",
	KindUintptr:    "Uintptr",
	KindFloat32:    "Float32",
	KindFloat64:    "Float64",
	KindComplex64:  "Complex64",
	KindComplex128: "Complex128",
	KindString:     "String",
	KindRune:       "Rune",
	KindByte:       "Byte",
	KindBoolean:    "Boolean",
	KindPointer:    "Pointer",
	KindStruct:     "Struct",
	KindFunc:       "Func",
	KindArray:      "Array",
	KindSlice:      "Slice",
	KindMap:        "Map",
	KindChannel:    "Channel",
	KindInterface:  "Interface",
}

var EnumValuesKind = map[string]Kind{
	"Nil":        KindNil,
	"Int":        KindInt,
	"Int8":       KindInt8,
	"Int16":      KindInt16,
	"Int32":      KindInt32,
	"Int64":      KindInt64,
	"Uint8":      KindUint8,
	"Uint16":     KindUint16,
	"Uint32":     KindUint32,
	"Uint64":     KindUint64,
	"Uintptr":    KindUintptr,
	"Float32":    KindFloat32,
	"Float64":    KindFloat64,
	"Complex64":  KindComplex64,
	"Complex128": KindComplex128,
	"String":     KindString,
	"Rune":       KindRune,
	"Byte":       KindByte,
	"Boolean":    KindBoolean,
	"Pointer":    KindPointer,
	"Struct":     KindStruct,
	"Func":       KindFunc,
	"Array":      KindArray,
	"Slice":      KindSlice,
	"Map":        KindMap,
	"Channel":    KindChannel,
	"Interface":  KindInterface,
}

func (v Kind) String() string {
	if s, ok := EnumNamesKind[v]; ok {
		return s
	}
	return "Kind(" + strconv.FormatInt(int64(v), 10) + ")"
}
