// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StructField struct {
	_tab flatbuffers.Table
}

func GetRootAsStructField(buf []byte, offset flatbuffers.UOffsetT) *StructField {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StructField{}
	x.Init(buf, n+offset)
	return x
}

func FinishStructFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsStructField(buf []byte, offset flatbuffers.UOffsetT) *StructField {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StructField{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedStructFieldBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *StructField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StructField) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StructField) Name() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StructField) MutateName(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *StructField) Type() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StructField) MutateType(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *StructField) Misc() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StructField) MutateMisc(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func StructFieldStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func StructFieldAddName(builder *flatbuffers.Builder, name uint32) {
	builder.PrependUint32Slot(0, name, 0)
}
func StructFieldAddType(builder *flatbuffers.Builder, type_ uint32) {
	builder.PrependUint32Slot(1, type_, 0)
}
func StructFieldAddMisc(builder *flatbuffers.Builder, misc uint32) {
	builder.PrependUint32Slot(2, misc, 0)
}
func StructFieldEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
