package compiler

import (
	"bytes"
	"log"
	"os"
	"sync"

	"github.com/Opticode-Project/go-compiler/go/golang"
	"github.com/Opticode-Project/go-compiler/program"
	flatbuffers "github.com/google/flatbuffers/go"
)

type GoFile struct {
	Path    string
	Content *[]byte
	nodes   *map[uint64]*DeserializeNode
}

func (gf *GoFile) Write(s string) error {
	return os.WriteFile(s, *gf.Content, 0644)
}

type DeserializeNode struct {
	Flags   golang.NodeFlag // Node flags
	Module  uint8           // Index of the nodes' module
	Content *[]byte         // Evaluated node content
	Span    [2]uint32       // File line span
}

type Generator struct {
	program *golang.App
	path    []uint64
	nodes   map[uint64]*program.Node

	deserializeNodes map[uint64]*DeserializeNode

	strLookupMutex  sync.Mutex
	typeLookupMutex sync.Mutex
	nodesMutex      sync.Mutex
}

func NewGenerator() *Generator {
	return &Generator{
		nodes: make(map[uint64]*program.Node),
		path:  []uint64{0},
	}
}

func (g *Generator) Listen(addr string) {
	server := &TCPServer{
		generator: g,
		builder:   flatbuffers.NewBuilder(256),
	}

	err := server.Start(addr)
	if err != nil {
		panic(err)
	}

	select {} // keep running
}

func (g *Generator) SetNode(node *program.Node) {
	g.nodes[node.Id()] = node
}

func (g *Generator) Compile(app *golang.App) {
	g.program = app
	g.deserializeNodes = make(map[uint64]*DeserializeNode, len(g.nodes))

	const maxRoutines = 5 // maximum allowed concurrent goroutines

	sem := make(chan struct{}, maxRoutines) // semaphore channel
	var wg sync.WaitGroup

	log.Printf("%v", g.path)
	for _, i := range g.path {
		if int64(i) == -1 {
			break
		}

		sem <- struct{}{} // acquire a "slot" (pauses if full)
		wg.Add(1)

		go func(index uint64) {
			defer wg.Done()
			defer func() { <-sem }() // release the slot when done

			node := g.nodes[index]
			log.Println(index, golang.Opcode(node.Opcode()), golang.NodeFlag(node.Flags()), int64(node.Next()))

			buf, err := g.Eval(node, 0)
			if err != nil {
				log.Println(err)
				return
			}

			g.nodesMutex.Lock()
			g.Write(node.Id(), golang.NodeFlag(node.Flags()), 0, &buf)
			g.nodesMutex.Unlock()
		}(i)
	}

	wg.Wait()
}

func (g *Generator) LookUpStr(i uint32) ([]byte, bool) {
	g.strLookupMutex.Lock()
	defer g.strLookupMutex.Unlock()

	var str program.StringEntry
	ok := g.program.LutByKey(&str, i)
	if !ok {
		return nil, false
	}
	return str.Value(), true
}

func (g *Generator) LookUpType(t uint32) (*golang.TypeDef, bool) {
	g.typeLookupMutex.Lock()
	defer g.typeLookupMutex.Unlock()

	var _type golang.TypeEntry
	ok := g.program.TypesByKey(&_type, t)
	if !ok {
		return nil, false
	}
	return _type.Value(nil), true
}

func (g *Generator) GetNode(id uint64) *program.Node {
	return g.nodes[id]
}

func (g *Generator) Write(id uint64, flags golang.NodeFlag, module uint8, content *[]byte) {
	g.deserializeNodes[id] = &DeserializeNode{
		Flags:   flags,
		Module:  module,
		Content: content,

		Span: [2]uint32{},
	}
}

func (g *Generator) Export(moduleId string, p []uint64) ([]*GoFile, error) {
	var out bytes.Buffer
	out.WriteString("// Code generated by the Opticode GO compiler. DO NOT EDIT.\n")

	for _, id := range p {
		if n, ok := g.deserializeNodes[id]; ok {
			// Add a transition seperator for lines with an extra line inbetween (e.g., Package -> Import)
			out.Grow(len(*n.Content))
			out.Write(*n.Content)
			out.WriteRune('\n')
		}
	}

	o := out.Bytes()

	t := &GoFile{
		Path:    moduleId,
		Content: &o,
		nodes:   &g.deserializeNodes,
	}

	return []*GoFile{t}, nil
}
