// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type Kind uint32

const (
	Kindnil        Kind = 0
	Kindint        Kind = 1
	Kindint8       Kind = 2
	Kindint16      Kind = 3
	Kindint32      Kind = 4
	Kindint64      Kind = 5
	Kinduint8      Kind = 6
	Kinduint16     Kind = 7
	Kinduint32     Kind = 8
	Kinduint64     Kind = 9
	Kinduintptr    Kind = 10
	Kindfloat32    Kind = 11
	Kindfloat64    Kind = 12
	Kindcomplex64  Kind = 13
	Kindcomplex128 Kind = 14
	Kindstring     Kind = 15
	Kindrune       Kind = 16
	Kindbyte       Kind = 17
	Kindboolean    Kind = 18
	Kindpointer    Kind = 19
	Kindstruct_     Kind = 20
	Kindfunc_       Kind = 21
	Kindarray      Kind = 22
	Kindslice      Kind = 23
	Kindmap_        Kind = 24
	Kindchannel    Kind = 25
	Kindinterface_  Kind = 26
)

var EnumNamesKind = map[Kind]string{
	Kindnil:        "nil",
	Kindint:        "int",
	Kindint8:       "int8",
	Kindint16:      "int16",
	Kindint32:      "int32",
	Kindint64:      "int64",
	Kinduint8:      "uint8",
	Kinduint16:     "uint16",
	Kinduint32:     "uint32",
	Kinduint64:     "uint64",
	Kinduintptr:    "uintptr",
	Kindfloat32:    "float32",
	Kindfloat64:    "float64",
	Kindcomplex64:  "complex64",
	Kindcomplex128: "complex128",
	Kindstring:     "string",
	Kindrune:       "rune",
	Kindbyte:       "byte",
	Kindboolean:    "boolean",
	Kindpointer:    "pointer",
	Kindstruct_:     "struct",
	Kindfunc_:       "func",
	Kindarray:      "array",
	Kindslice:      "slice",
	Kindmap_:        "map",
	Kindchannel:    "channel",
	Kindinterface_:  "interface",
}

var EnumValuesKind = map[string]Kind{
	"nil":        Kindnil,
	"int":        Kindint,
	"int8":       Kindint8,
	"int16":      Kindint16,
	"int32":      Kindint32,
	"int64":      Kindint64,
	"uint8":      Kinduint8,
	"uint16":     Kinduint16,
	"uint32":     Kinduint32,
	"uint64":     Kinduint64,
	"uintptr":    Kinduintptr,
	"float32":    Kindfloat32,
	"float64":    Kindfloat64,
	"complex64":  Kindcomplex64,
	"complex128": Kindcomplex128,
	"string":     Kindstring,
	"rune":       Kindrune,
	"byte":       Kindbyte,
	"boolean":    Kindboolean,
	"pointer":    Kindpointer,
	"struct":     Kindstruct_,
	"func":       Kindfunc_,
	"array":      Kindarray,
	"slice":      Kindslice,
	"map":        Kindmap_,
	"channel":    Kindchannel,
	"interface":  Kindinterface_,
}

func (v Kind) String() string {
	if s, ok := EnumNamesKind[v]; ok {
		return s
	}
	return "Kind(" + strconv.FormatInt(int64(v), 10) + ")"
}
