// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type NodeFlag uint32

const (
	NodeFlagNone        NodeFlag = 1
	NodeFlagNodeIndexed NodeFlag = 2
	NodeFlagNodeBinary  NodeFlag = 4
	NodeFlagNodeUnary   NodeFlag = 8
)

var EnumNamesNodeFlag = map[NodeFlag]string{
	NodeFlagNone:        "None",
	NodeFlagNodeIndexed: "NodeIndexed",
	NodeFlagNodeBinary:  "NodeBinary",
	NodeFlagNodeUnary:   "NodeUnary",
}

var EnumValuesNodeFlag = map[string]NodeFlag{
	"None":        NodeFlagNone,
	"NodeIndexed": NodeFlagNodeIndexed,
	"NodeBinary":  NodeFlagNodeBinary,
	"NodeUnary":   NodeFlagNodeUnary,
}

func (v NodeFlag) String() string {
	if s, ok := EnumNamesNodeFlag[v]; ok {
		return s
	}
	return "NodeFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
