// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StructField struct {
	_tab flatbuffers.Struct
}

func (rcv *StructField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StructField) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *StructField) Name() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *StructField) MutateName(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *StructField) Type() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(4))
}
func (rcv *StructField) MutateType(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(4), n)
}

func (rcv *StructField) Misc() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *StructField) MutateMisc(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateStructField(builder *flatbuffers.Builder, name uint32, type_ uint32, misc uint32) flatbuffers.UOffsetT {
	builder.Prep(4, 12)
	builder.PrependUint32(misc)
	builder.PrependUint32(type_)
	builder.PrependUint32(name)
	return builder.Offset()
}
