// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package golang

import "strconv"

type ValueFlag uint32

const (
	ValueFlagNone          ValueFlag = 1
	ValueFlagPointer       ValueFlag = 2
	ValueFlagQuotation     ValueFlag = 4
	ValueFlagIfConditon    ValueFlag = 8
	ValueFlagIfBody        ValueFlag = 16
	ValueFlagIfElse        ValueFlag = 32
	ValueFlagFuncMeta      ValueFlag = 64
	ValueFlagFuncParam     ValueFlag = 128
	ValueFlagFuncBody      ValueFlag = 256
	ValueFlagSwitchExp     ValueFlag = 512
	ValueFlagSwitchBody    ValueFlag = 1024
	ValueFlagCaseExp       ValueFlag = 2048
	ValueFlagCaseBody      ValueFlag = 4096
	ValueFlagForInit       ValueFlag = 8192
	ValueFlagForCondition  ValueFlag = 16384
	ValueFlagForPost       ValueFlag = 32768
	ValueFlagForBody       ValueFlag = 65536
	ValueFlagForRangeVar1  ValueFlag = 131072
	ValueFlagForRangeVar2  ValueFlag = 262144
	ValueFlagForRangeValue ValueFlag = 524288
	ValueFlagDefaultBody   ValueFlag = 1048576
)

var EnumNamesValueFlag = map[ValueFlag]string{
	ValueFlagNone:          "None",
	ValueFlagPointer:       "Pointer",
	ValueFlagQuotation:     "Quotation",
	ValueFlagIfConditon:    "IfConditon",
	ValueFlagIfBody:        "IfBody",
	ValueFlagIfElse:        "IfElse",
	ValueFlagFuncMeta:      "FuncMeta",
	ValueFlagFuncParam:     "FuncParam",
	ValueFlagFuncBody:      "FuncBody",
	ValueFlagSwitchExp:     "SwitchExp",
	ValueFlagSwitchBody:    "SwitchBody",
	ValueFlagCaseExp:       "CaseExp",
	ValueFlagCaseBody:      "CaseBody",
	ValueFlagForInit:       "ForInit",
	ValueFlagForCondition:  "ForCondition",
	ValueFlagForPost:       "ForPost",
	ValueFlagForBody:       "ForBody",
	ValueFlagForRangeVar1:  "ForRangeVar1",
	ValueFlagForRangeVar2:  "ForRangeVar2",
	ValueFlagForRangeValue: "ForRangeValue",
	ValueFlagDefaultBody:   "DefaultBody",
}

var EnumValuesValueFlag = map[string]ValueFlag{
	"None":          ValueFlagNone,
	"Pointer":       ValueFlagPointer,
	"Quotation":     ValueFlagQuotation,
	"IfConditon":    ValueFlagIfConditon,
	"IfBody":        ValueFlagIfBody,
	"IfElse":        ValueFlagIfElse,
	"FuncMeta":      ValueFlagFuncMeta,
	"FuncParam":     ValueFlagFuncParam,
	"FuncBody":      ValueFlagFuncBody,
	"SwitchExp":     ValueFlagSwitchExp,
	"SwitchBody":    ValueFlagSwitchBody,
	"CaseExp":       ValueFlagCaseExp,
	"CaseBody":      ValueFlagCaseBody,
	"ForInit":       ValueFlagForInit,
	"ForCondition":  ValueFlagForCondition,
	"ForPost":       ValueFlagForPost,
	"ForBody":       ValueFlagForBody,
	"ForRangeVar1":  ValueFlagForRangeVar1,
	"ForRangeVar2":  ValueFlagForRangeVar2,
	"ForRangeValue": ValueFlagForRangeValue,
	"DefaultBody":   ValueFlagDefaultBody,
}

func (v ValueFlag) String() string {
	if s, ok := EnumNamesValueFlag[v]; ok {
		return s
	}
	return "ValueFlag(" + strconv.FormatInt(int64(v), 10) + ")"
}
