// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package network

import "strconv"

type ID uint16

const (
	IDVerification  ID = 0
	IDRVerification ID = 1
)

var EnumNamesID = map[ID]string{
	IDVerification:  "Verification",
	IDRVerification: "RVerification",
}

var EnumValuesID = map[string]ID{
	"Verification":  IDVerification,
	"RVerification": IDRVerification,
}

func (v ID) String() string {
	if s, ok := EnumNamesID[v]; ok {
		return s
	}
	return "ID(" + strconv.FormatInt(int64(v), 10) + ")"
}
