// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import "strconv"

type Flag uint32

const (
	FlagFirstSegment  Flag = 1
	FlagSecondSegment Flag = 2
	FlagThirdSegment  Flag = 4
	FlagForthSegment  Flag = 8
)

var EnumNamesFlag = map[Flag]string{
	FlagFirstSegment:  "FirstSegment",
	FlagSecondSegment: "SecondSegment",
	FlagThirdSegment:  "ThirdSegment",
	FlagForthSegment:  "ForthSegment",
}

var EnumValuesFlag = map[string]Flag{
	"FirstSegment":  FlagFirstSegment,
	"SecondSegment": FlagSecondSegment,
	"ThirdSegment":  FlagThirdSegment,
	"ForthSegment":  FlagForthSegment,
}

func (v Flag) String() string {
	if s, ok := EnumNamesFlag[v]; ok {
		return s
	}
	return "Flag(" + strconv.FormatInt(int64(v), 10) + ")"
}
