// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NodeValue struct {
	_tab flatbuffers.Struct
}

func (rcv *NodeValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NodeValue) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *NodeValue) Value() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *NodeValue) MutateValue(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *NodeValue) Type() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *NodeValue) MutateType(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func (rcv *NodeValue) Flags() uint32 {
	return rcv._tab.GetUint32(rcv._tab.Pos + flatbuffers.UOffsetT(12))
}
func (rcv *NodeValue) MutateFlags(n uint32) bool {
	return rcv._tab.MutateUint32(rcv._tab.Pos+flatbuffers.UOffsetT(12), n)
}

func CreateNodeValue(builder *flatbuffers.Builder, value uint64, type_ uint32, flags uint32) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint32(flags)
	builder.PrependUint32(type_)
	builder.PrependUint64(value)
	return builder.Offset()
}
