// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package program

import "strconv"

type Type byte

const (
	TypeNONE          Type = 0
	Typegolang_GoType Type = 1
)

var EnumNamesType = map[Type]string{
	TypeNONE:          "NONE",
	Typegolang_GoType: "golang_GoType",
}

var EnumValuesType = map[string]Type{
	"NONE":          TypeNONE,
	"golang_GoType": Typegolang_GoType,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
